spring:
  mvc:
    view:
      suffix: .html
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  profiles:
    include: oauth

  datasource:
    hikari:
      validation-timeout: '10000'
      connection-timeout: '10000'
      idle-timeout: '10000'
      maximum-pool-size: '10'
      max-lifetime: '420000'
    tomcat:
      testOnBorrow: 'true'
      validationQuery: SELECT 1
      min-evictable-idle-time-millis: '7200000'
      time-between-eviction-runs-millis: '3600000'
      test-while-idle: 'true'
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springBoard?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    database: mysql
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
server:
  port: '9080'
